create table if not exists public.fortunes (
  id bigint generated by default as identity primary key,
  line_user_id text not null,
  fortune_date date not null,
  fortune_result text not null,
  created_at timestamptz not null default now(),
  constraint fortunes_user_date_unique unique (line_user_id, fortune_date)
);

alter table public.fortunes enable row level security;

grant select, insert on table public.fortunes to service_role;
grant usage, select on sequence public.fortunes_id_seq to service_role;
