create table if not exists public.fortunes_tw (
  id bigint generated by default as identity primary key,
  line_user_id text not null,
  fortune_date date not null,
  fortune_result text not null,
  created_at timestamptz not null default now(),
  constraint fortunes_tw_user_date_unique unique (line_user_id, fortune_date)
);

alter table public.fortunes_tw enable row level security;

revoke all privileges on table public.fortunes_tw from anon, authenticated;
revoke all privileges on sequence public.fortunes_tw_id_seq from anon, authenticated;

grant select, insert on table public.fortunes_tw to service_role;
grant usage, select on sequence public.fortunes_tw_id_seq to service_role;
